language: python
sudo: false
dist: trusty
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x

matrix:
  include:
    - python: '2.7'
      env:
        - TOXENV=py27
    - python: '3.4'
      env:
        - TOXENV=py34
    - python: '3.5'
      env:
        - TOXENV=py35
    - python: '3.6'
      env:
        - TOXENV=py36
    - python: '3.7'
      env:
        - TOXENV=py37
      dist: xenial
      sudo: true
    - python: '3.8'
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-8
            - g++-8
      env:
        - TOXENV=py38
      dist: xenial
      sudo: true
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=coverage

before_install:
  - gcc --version

install:
  - pip install -U tox codecov

script:
  - tox -- -v

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
